name: ci

on:
  push:
    branches: [ 'main' ]
    tags:     [ '*' ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/valheim-server-aws:latest
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/valheim-server-aws:buildcache
          cache-to:   type=registry,ref=${{ secrets.DOCKER_USERNAME }}/valheim-server-aws:buildcache,mode=max
